name: Build MimiLauncher JAR

on:
  push:
    branches: [ "master", "main", "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Is step mein cache disable ki hai aur JVM arguments lagaye hain error bypass karne ke liye
      - name: Build with Gradle
        run: ./gradlew assemble --no-configuration-cache -Dorg.gradle.jvmargs="--add-opens=java.base/java.util.concurrent=ALL-UNNAMED"

      - name: Upload MimiLauncher JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MimiLauncher-JAR
          path: '**/build/libs/*.jar'
